# è¿‡æ»¤æ–‡ä»¶åç§°ã€ç›®å½•ã€åç¼€ã€å‰ç¼€ï¼Œåç§°ä¹‹é—´ç”¨è‹±æ–‡,å·éš”å¼€ï¼Œä¾‹å¦‚ï¼štest.txt,1.txtï¼›è¿‡æ»¤é¡ºåºï¼šç›®å½• ğŸ‘‰ æ–‡ä»¶ ğŸ‘‰ åç¼€ ğŸ‘‰ å‰ç¼€ï¼›æ³¨æ„ï¼šå¦‚æœæ˜¯ç›®å½•ï¼Œæœ€åä¸ç”¨åŠ æ–‡ä»¶åˆ†éš”ç¬¦
no-permission:
  enable: true
  filter:
    directory: E:\hxInvoicingSystemLogs\test1,E:\log
    file: test.txt,1.txt
    suffix: .log
    prefix: test_

# æŒ‡å®šè·¯å¾„
specified-path:
  enable: true
  directory: E:\hxInvoicingSystemLogs,E:\log1